### ISSUE TITLE
Notify isn't called

### ISSUE THREAD

**Issue by iharsuvorau** [jkallio/pomodoro-cli#6]
Hey, great thanks for the tool. Thought, it looks like when running it with `pomodoro-cli --notify` doesn't notify after the duration until I query for the status with `pomodoro-cli status` — then, it notifies and reports the negative duration.

**Comment by jkallio** [comment]
This is actually the way this tool was designed. You need a separate system (e.g. Waybar) to poll the status periodically.

...or, alternatively, you can use the tool directly from command line and provide the `--wait` flag which will keep the application running until the timer has expired.
